### ISSUE TITLE
Validating Haxby Dataset

### ISSUE THREAD

**Issue by sajjadtorabian** [bids-standard/legacy-validator#406]
Hi, I'm having an issue with validating a version of Haxby dataset (https://openfmri.org/dataset/ds000105/). The latest versions seem to be in BIDS format already. But it is taking too long for the validator to validate (20 minutes now), and I don't think it's gonna work!

**Comment by chrisgorgo** [comment]
I can replicate:

```
Uncaught TypeError: a.existsSync is not a function
    at Object.start [as BIDS] (app.min.js? [sm]:13351)
    at n.<anonymous> (app.min.js? [sm]:92219)
    at n.t [as validate] (app.min.js? [sm]:92208)
    at n.onChange (app.min.js? [sm]:92197)
    at i.n (app.min.js? [sm]:89146)
    at i.emit (app.min.js? [sm]:25287)
    at Function.trigger (app.min.js? [sm]:89215)
    at app.min.js? [sm]:89226
```

**Comment by chrisgorgo** [comment]
Seems to happen only with the online version. I think it was introduced by #401

**Comment by chrisgorgo** [comment]
Should be fixed now.

**Comment by SetCodesToFire** [comment]
Can I know how to get this fixed @chrisfilo

**Comment by chrisgorgo** [comment]
If I knew I would've done it myself ;)

I would start with replicating the error with the web version of the validator built by circleci for your original pull request https://946-37161308-gh.circle-artifacts.com/0/home/ubuntu/web_version/index.html and study the dev console. Then I would build a local version of the web validator (see instructions https://github.com/INCF/bids-validator#running-locally-in-a-browser) and try to debug it.

**Comment by sajjadtorabian** [comment]
I downloaded the initial release of the dataset, converted it to BIDS using openfmri2bids, and then validated it with the command line version, but it doesn't seem like it is converted properly. I get two errors (REPETITION_TIME_MISMATCH and SFORM_AND_QFORM_IN_IMAGE_HEADER_ARE_ZERO) and three warnings (SLICE_TIMING_NOT_DEFINED and INCONSISTENT_SUBJECTS and INCONSISTENT_PARAMETERS).

I think I can ignore the second warning because it is just about one subject missing a run. But I'm not sure how to fix the other issues. I tried using the latest version of the dataset which is already converted to BIDS, but faced the same thing (except the first error). Could you please take a look at this on your machine whenever you have a chance? I can also share more details of the validator's output.

Is there any other source which has the Haxby dataset in BIDS? Thank you!

**Comment by chrisgorgo** [comment]
The bidsified version you downloaded (which is also available at https://openneuro.org/datasets/ds000105/versions/00001) is the best you can and that is unlikely to change due to metadata that was not originaly provided and later lost by the data producers (see https://openfmri.org/dataset-orientation-issues/ for more details).

Things will improve with future datasets thanks to all the issues that can be automatically caught by the validator.

**Comment by sajjadtorabian** [comment]
Thank you! Good to know about the availability of the dataset on OpenNeuro. I was trying to run fmriprep which is already done there.

**Comment by SetCodesToFire** [comment]
Is the error only due to the file headers? @chrisfilo 
I think the dataset used while creating this error in the tray, does include time mismatching between nifti and json file's header. As well as either no value for sform and qform properties or they are undefined.

**Comment by SetCodesToFire** [comment]
The last revision of the Haxby dataset (https://openfmri.org/dataset/ds000105/) is Revision: 2.0.2 Date Set: Oct. 28, 2016, 
The BIDS specification for checking particular headers as well as checking the repetition time could have been included after this time period.

**Comment by chrisgorgo** [comment]
Not sure what you mean by "this error in the tray". 

Yes the validator is more strict than it used to be.

Please mind that this is a problem with a dataset not the validator.

**Comment by SetCodesToFire** [comment]
Yes which is what I am trying to say, the validator has included new rules from the date stamp: November 2016 version 0.19.5 to the present version

**Comment by SetCodesToFire** [comment]
By this "error in the tray" I mean there are two issues while validating the dataset.
 1)  REPETITION_TIME_MISMATCH  SFORM_ (Issue code 12)
  2) _QFORM_IN_IMAGE_HEADER_ARE_ZERO (Issue code 60

**Comment by SetCodesToFire** [comment]
Additionaly we could perform a check if there is a date-stamp in the header of the dataset, and relative to that we could perform the bids validation?

**Comment by chrisgorgo** [comment]
I think you are missing the point here. [The error](https://github.com/INCF/bids-validator/issues/406#issuecomment-367473577) @sajjadtorabian run into originally was introduced by your [PR ](https://github.com/INCF/bids-validator/pull/401)(which I later had to [revert](https://github.com/INCF/bids-validator/pull/407)). It had nothing to do with ds000105 having header issues.

Sorry for the noise @sajjadtorabian. @SetCodesToFire is new to the project and is trying to get recruited as part of Google Summer of Code.

**Comment by SetCodesToFire** [comment]
Yes, I am sorry @sajjadtorabian and @chrisfilo 
I think i am over-excited and have a fear of missing out from this opportunity

**Comment by sajjadtorabian** [comment]
It's fine, Chris! I'm learning from the comments.
